// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaQlSUwCnoQHkct0SJAq8fTChAe1BnieU',
    appId: '1:438545075754:web:008412a85eae67eaf47d53',
    messagingSenderId: '438545075754',
    projectId: 'hiring-competitions-ff5cd',
    authDomain: 'hiring-competitions-ff5cd.firebaseapp.com',
    storageBucket: 'hiring-competitions-ff5cd.firebasestorage.app',
    measurementId: 'G-0FJD85FP1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv2DZUWmD6kfpjopwxtyn5nnFBsb5oTro',
    appId: '1:438545075754:android:28dbb72bcdffd744f47d53',
    messagingSenderId: '438545075754',
    projectId: 'hiring-competitions-ff5cd',
    storageBucket: 'hiring-competitions-ff5cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAiKPEC_ZTvl8Wu3v-0C13HC6G6IH8CcI',
    appId: '1:438545075754:ios:bc0425bcc0443969f47d53',
    messagingSenderId: '438545075754',
    projectId: 'hiring-competitions-ff5cd',
    storageBucket: 'hiring-competitions-ff5cd.firebasestorage.app',
    androidClientId: '438545075754-bin9uf7vnq0k5pqjigd7h46docpvho06.apps.googleusercontent.com',
    iosClientId: '438545075754-cto55u9clbf4t4nrjp71c366gjk7fg4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiringCompetitionsAdminPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAiKPEC_ZTvl8Wu3v-0C13HC6G6IH8CcI',
    appId: '1:438545075754:ios:bc0425bcc0443969f47d53',
    messagingSenderId: '438545075754',
    projectId: 'hiring-competitions-ff5cd',
    storageBucket: 'hiring-competitions-ff5cd.firebasestorage.app',
    androidClientId: '438545075754-bin9uf7vnq0k5pqjigd7h46docpvho06.apps.googleusercontent.com',
    iosClientId: '438545075754-cto55u9clbf4t4nrjp71c366gjk7fg4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiringCompetitionsAdminPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaQlSUwCnoQHkct0SJAq8fTChAe1BnieU',
    appId: '1:438545075754:web:d94ab83b67f1a989f47d53',
    messagingSenderId: '438545075754',
    projectId: 'hiring-competitions-ff5cd',
    authDomain: 'hiring-competitions-ff5cd.firebaseapp.com',
    storageBucket: 'hiring-competitions-ff5cd.firebasestorage.app',
    measurementId: 'G-ZMXS43DGW4',
  );
}
